name: Build and Test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  ubuntu:
    name: AMD64 Ubuntu 24.04
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Checkout kernel-loader
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: kernel-loader
          environment-file: ci/environment.yml
          auto-activate-base: false
      - name: Build
        shell: bash
        run: ci/scripts/build_kernel_loader.sh $(pwd)
      - name: Test Python
        shell: bash
        run: python test_load.py